pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -DskipTests clean package '
            }
        }
        stage('Test'){
            steps {

            }
        }
        stage('Deploy') {
            steps {

            }
        }
    }
}