pipeline {
    agent {
        docker {
            image 'maven:3.9.8-eclipse-temurin-17'
            args '--add-host=host.docker.internal:host-gateway'
        }
    }
    environment {
        DOCKER_HOST = 'tcp://host.docker.internal:2375'
        DOCKER_TLS_VERIFY = '0'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    }
}
