name: scholarlymail

services:
  mongodb:
    image: mongo:4.4.18
    ports:
      - "27017:27017"
    networks:
      - scholarlymail

  web:
    build: .
    ports:
     - "8081:8081"
    image: scholarlymail
    networks:
      - scholarlymail

networks:
  # The presence of these objects is sufficient to define them
  scholarlymail: {}
